---
apiVersion : apps/v1
kind: Deployment

metadata:
  name: nwapp-deploy
  namespace: nwdb
  labels:
    name: northwind_app
    version: v1

spec:
  # number of pods
  replicas: 3
  minReadySeconds: 60
  selector: 
    matchLabels:
      name: northwind_app
      version: v1
  template:
    metadata:
      # pod template
      name: nwapp-pod
      labels:
        name: northwind_app
        version: v1
    spec:
      containers:
      - name: nwapp-container
        image: josephlimys/northwind_server:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nwapp-config
              key: db_host
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: nwapp-config
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nwdb-secret
              key: db_password 
        ports:
        - name: http-port
          containerPort: 3000
---
apiVersion: v1
kind: Service

metadata:
  name: nwapp-svc
  namespace: nwdb
  labels:
    name: nwapp-svc
    version: v1

spec:
  type: LoadBalancer
  selector:
    name: northwind_app
    version: v1
  ports:
    - name: http-svc
      port: 80
      targetPort: http-port
      protocol: TCP