FROM node:latest

# How an image is build
# Set environment variables
ENV APP_ROOT=/app APP_PORT=3000

# Create directory and cd into it
WORKDIR ${APP_ROOT}

# Copy Files into the image
# files will be copied into /app
ADD main.js .
ADD package.json .
ADD public public
ADD views views

# Install dependencies
RUN npm install

# How an image is provisioned

# Expose Port
EXPOSE ${APP_PORT}/tcp

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
    CMD curl -s -f http://localhost:${APP_PORT}/health > /dev/null || exit 1

ENTRYPOINT [ "node", "main.js" ]
CMD [ "" ]
# If Additional Arguments (node main.js 3000)
#CMD [ "" ]
#CMD [ "3000" ]

# RUN => executed during build time
# ENTRYPOINT, CMD => execution time