version: '3'

networks: 
  appnet:
  
volumes:
  appvol:

services:
  db:
    image: josephlimys/northwind_db:v1
    build: 
      context: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
    volumes:
      - appvol:/var/lib/mysql
    networks:
      - appnet
    
  app:
    image: josephlimys/northwind_server:v1
    build:
      context: ./server
    environment:
      - DB_HOST=db
    networks:
      - appnet
    ports:
      - 80:3000  

